---
- name: Create resource group
  include_role:
    name: resource_group
  when: rg_info.resourcegroups | length == 0

- name: Ensure public ip exists
  block:
    - name: Get public ip info
      azure_rm_publicipaddress_info:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_load_balancer.public_ip_name | default(azure_load_balancer.name + '-public-ip') }}"
      register: lb_ip_info

    - name: Create public ip
      azure_rm_publicipaddress:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_load_balancer.public_ip_name | default(azure_load_balancer.name + '-public-ip') }}"
        domain_name: "{{ azure_load_balancer.domain_name | default(omit) }}"
      # when: lb_ip_info.publicipaddresses | length == 0

- name: Create/Update load balancer
  azure_rm_loadbalancer:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_load_balancer.name }}"
    frontend_ip_configurations:
      - name: "frontend"
        public_ip_address: "{{ azure_load_balancer.public_ip_name | default(azure_load_balancer.name + '-public-ip') }}"
    backend_address_pools: "{{ azure_load_balancer.backend_address_pool | default([{ 'name': azure_load_balancer.name + '-backend-pool' }]) }}"
    probes: "{{ azure_load_balancer.probes | default(omit) }}"
    load_balancing_rules: "{{ azure_load_balancer.rules | default(omit) }}"
    sku: "{{ azure_load_balancer.sku | default(omit) }}"
    tags: "{{ azure_load_balancer.tags | default(omit) }}"

- name: Attach NICs if input
  include_role:
    name: cloud.azure_roles.network_interface
  with_items: "{{ azure_lb_network_interface_instances }}"
  loop_control:
    loop_var: azure_network_interface_name
  when:
    - azure_lb_network_interface_instances is defined
    - azure_lb_network_interface_instances | length > 0
