---
- name: Assert resource group '{{ azure_resource_group }}' exists
  fail:
    msg: "Resource group '{{ azure_resource_group }}' does not exist."
  when:
    - rg_info.resourcegroups | length == 0

- name: Get lb's public ip info
  azure_rm_resource_info:
    url: "{{ lb_info.ansible_info.azure_loadbalancers[0].properties.frontendIPConfigurations[0].properties.publicIPAddress.id }}"
  register: pip

- name: Delete load balancer
  azure_rm_loadbalancer:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_load_balancer.name }}"
    state: absent

- name: Delete load balancer's public ip
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ pip.response[0].name }}"
    state: absent