---
- name: Check Region Setting
  fail:
    msg: "Azure Region must be defined as azure_region"
  when: azure_region is not defined

- name: Check Resource Group Exists
  azure_rm_resourcegroup_info:
    name: "{{ azure_resource_group }}"
  register: result

- name: Resource Group Does Not Exist -> Create Resource Group
  include_role:
    name: resource_group
  when: result.resourcegroups | length == 0

- name: Create an Availability Set
  azure_rm_availabilityset:
    resource_group: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"
    name: "{{ azure_availability_set_name }}"
