---
- name: Check Region Setting
  fail:
    msg: "Azure Region must be defined as azure_region"
  when: azure_region is not defined

- name: Check Resource Group Exists
  azure_rm_resourcegroup_info:
    name: "{{ azure_resource_group }}"
  register: result

- name: Resource Group Does Not Exist -> Exit
  debug:
    msg: 'Resource group {{ azure_resource_group }} does not exist.'
  when: result.resourcegroups | length == 0  

- name: Delete an Availability Set
  azure_rm_availabilityset:
    resource_group: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"
    name: "{{ azure_availability_set_name }}"
    state: absent
  when: result.resourcegroups | length != 0  