---
- block:
    - name: Lookup VM's NIC
      azure_rm_virtualmachine_info:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ vm }}"
      register: vm_info      
    
    - assert:
        that:
          - vm_info.vms | length == 1
          - vm_info.vms[0].network_interface_names | length == 1

    - name: Attach NIC to load balancer
      include_role:
        name: network_interface
      vars:
        azure_network_interface_name: "{{ vm_info.vms[0].network_interface_names[0] }}"
        operation: 'attach'     