---
- name: Ensure admin username is defined
  fail:
    msg: "Azure VM admin username must be defined as azure_vm_admin_username"
  when: azure_vm_admin_username is not defined

- name: Ensure vm size is defined
  fail:
    msg: "Azure VM size must be defined as azure_vm_size"
  when: azure_vm_size is not defined

- name: Ensure vm image is defined
  fail:
    msg: "Azure VM image must be defined as azure_vm_image"
  when: azure_vm_image is not defined

- name: Resource Group Does Not Exist -> Create Resource Group
  include_role:
    name: resource_group
  when: rg_info.resourcegroups | length == 0

# If NIC is not specified, assert virtual network exists
- block:
  - name: No network interface specified -> get virtual network info
    azure_rm_virtualnetwork_info:
      resource_group: "{{ azure_resource_group }}"
    register: vnet_info

  - name: Ensure vnet exists
    fail:
      msg: 'When no NIC is specified, a virtual network must exist'
    when: vnet_info.virtualnetworks | length == 0
  when: azure_network_interface_name is undefined

# If NIC is specified, assert it exists
- name: Network interface specified -> assert it exists
  include_role:
    name: cloud.azure_roles.network_interface
  when: azure_network_interface_name is defined

# Tag VM's public ip when its not autogenerated
- name: Tag VM's public ip name
  block:
    - name: Get public ip info
      azure_rm_publicipaddress_info:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_public_ip_name }}"
      register: vm_pip_info

    - name: Append VM's _own_pip_ tag to existing dict of tags
      set_fact:
        azure_tags: "{{ azure_tags | combine({ '_own_pip_': vm_pip_info.publicipaddresses[0].name }) }}"
  when: azure_public_ip_name is defined

# Assert specified availability set is created
- block:
  - name: Get availability set info
    azure_rm_availabilityset_info:
      resource_group: "{{ azure_resource_group }}"
      name: "{{ azure_availability_set_name }}"
    register: as_info

  - name: Create availability set '{{ azure_availability_set_name }}'
    azure_rm_availabilityset:
      resource_group: "{{ azure_resource_group }}"
      name: "{{ azure_availability_set_name }}"
    when: as_info.ansible_info.azure_availabilitysets | length == 0
  when: azure_availability_set_name is defined

- name: Create a VM
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}"
    vm_size: "{{ azure_vm_size }}"
    network_interfaces: "{{ azure_network_interface_name | default(omit) }}"
    os_type: "{{ azure_vm_os | default(omit) }}"
    availability_set: "{{ azure_availability_set_name | default(omit) }}"
    image: "{{ azure_vm_image }}"
    admin_username: "{{ azure_vm_admin_username }}"
    admin_password: "{{ azure_vm_admin_password | default(omit) }}"
    ssh_password_enabled: "{{ azure_vm_ssh_pw_enabled | default(omit) }}"
    ssh_public_keys: "{{ azure_vm_ssh_public_keys | default(omit) }}"
    data_disks: "{{ azure_vm_data_disks | default(omit) }}"
    tags: "{{ azure_tags | default(omit) }}"