---
- name: Check Region Setting
  fail:
    msg: "Azure Region must be defined as azure_region"
  when: azure_region is not defined

- name: Check Resource Group Exists
  azure_rm_resourcegroup_info:
    name: "{{ azure_resource_group }}"
  register: result

- name: Resource Group Does Not Exist -> Exit
  debug:
    msg: 'Resource group {{ azure_resource_group }} does not exist.'
  when: result.resourcegroups | length == 0  

- name: Delete Virtual Machine
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}"
    remove_on_absent: "{{ remove_on_absent }}"
    state: absent
  when: result.resourcegroups | length != 0  