---
- name: Check operation validation
  fail:
    msg: "Please provide operation as 'create' or 'delete'"
  when: operation not in ['create', 'delete']

- name: Check resource group name
  fail:
    msg: "Azure Resource group name must be defined as azure_resource_group"
  when: azure_resource_group is not defined

- name: Check security group name
  fail:
    msg: "Azure security group name must be defined as azure_security_group"
  when: azure_security_group is not defined

- name: Get resource group info
  azure_rm_resourcegroup_info:
    name: "{{ azure_resource_group }}"
  register: rg_info

- include_tasks: "{{ operation }}.yml"
