---
- name: Check Region Setting
  fail:
    msg: "Azure Region must be defined as azure_region"
  when: azure_region is not defined

- name: Check Resource Group Exists
  azure_rm_resourcegroup_info:
    name: "{{ azure_resource_group }}"
  register: result

- name: Resource Group Does Not Exist -> Create Resource Group
  include_role:
    name: resource_group
  when: result.resourcegroups | length == 0

- name: Create a Public IP
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_public_ip_name }}"
    allocation_method: Static
    location: canadacentral
  register: output_ip_address

- name: Output public IP
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}"
