---
- name: Check Resource Group Exists
  azure_rm_resourcegroup_info:
    name: "{{ azure_resource_group }}"
  register: result

- name: Resource Group Does Not Exist -> Exit
  debug:
    msg: 'Resource group {{ azure_resource_group }} does not exist.'
  when: result.resourcegroups | length == 0

- name: Delete Public IP
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_public_ip_name }}"
    state: absent
  when: result.resourcegroups | length != 0