---
- name: Check Region Setting
  fail:
    msg: "Azure Region must be defined as azure_region"
  when: azure_region is not defined

- name: Check Resource Group Exists
  azure_rm_resourcegroup_info:
    name: "{{ azure_resource_group }}"
  register: result

- name: Resource Group Does Not Exist -> Create Resource Group
  include_role:
    name: resource_group
  when: result.resourcegroups | length == 0

- name: Check Networking Stack Exists
  azure_rm_virtualnetwork_info:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_virtual_network }}"
  register: virtual_network_result

- name: Networking Stack Does Not Exist -> Create Networking Stack
  include_role:
    name: networking_stack
  when: virtual_network_result.virtualnetworks | length == 0  

- name: Check Security Group Exists
  azure_rm_securitygroup_info:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_security_group_name }}"
  register: security_group_result

- name: Security Group Does Not Exist -> Create Security Group
  include_role:
    name: security_group
  when: security_group_result.securitygroups | length == 0  

- name: Check Public IP Exists
  azure_rm_publicipaddress_info:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_public_ip_name }}"
  register: public_ip_result

- name: Public IP Does Not Exist -> Create Public IP
  include_role:
    name: public_ip
  when: public_ip_result.publicipaddresses | length == 0  

- name: Create a Network Interface
  azure_rm_networkinterface:
    name: "{{ azure_nw_interface }}"
    resource_group: "{{ azure_resource_group }}"
    virtual_network: "{{ azure_virtual_network }}"
    subnet_name: "{{ azure_subnet }}"
    security_group: "{{ azure_security_group_name }}"
    ip_configurations:
      - name: default
        public_ip_address_name: "{{ azure_public_ip_name }}"
        primary: True
