operation: "create"

azure_tags:
  application: "python-demo-webapp-for-ansible-cloud-team"

# Networking variables
azure_virtual_network: "{{ azure_resource_group }}-vnet"
azure_subnet: "{{ azure_resource_group }}-subnet"
azure_vnet_address_prefixes_cidr:
- 10.1.0.0/16
azure_subnet_address_prefixes_cidr: 10.1.0.0/24
azure_security_group: "{{ azure_resource_group }}-nsg"

# Load Balancer
azure_lb_name: "{{ azure_resource_group }}-lb"
azure_network_interface_instances: []

