---
- name: Use awx collection to create a project
  hosts: localhost
  gather_facts: no
  collections:
    - awx.awx
  vars_files:
    - vars/main.yml
  tasks:
    - name: Create awx project
      awx.awx.project:
        name: "{{ project_name }}"
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        scm_type: git
        scm_url: "{{ scm_url }}"
        scm_branch: "{{ scm_branch | default(omit) }}"
        credential: "{{ project_name }}_scm"
        organization: '{{ controller_org | default("Default") }}'
        scm_update_on_launch: True
        state: present