---
- name: Check that resource group exists
  azure.azcollection.azure_rm_resourcegroup_info:
    name: "{{ azure_manage_networking_stack_resource_group }}"
  register: result

- name: Create resource group when it does not exists
  ansible.builtin.include_role:
    name: cloud.azure_ops.azure_manage_resource_group
  vars:
    azure_manage_resource_group_operation: create
    azure_manage_resource_group_name: "{{ azure_manage_networking_stack_resource_group }}"
    azure_manage_resource_group_region: "{{ azure_manage_networking_stack_region }}"
    azure_manage_resource_group_tags: "{{ azure_manage_networking_stack_tags }}"
  when: result.resourcegroups | length == 0

- name: Create azure virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    location: "{{ azure_manage_networking_stack_region }}"
    name: "{{ azure_manage_networking_stack_virtual_network }}"
    address_prefixes_cidr: "{{ azure_manage_networking_stack_vnet_address_prefixes_cidr }}"
    resource_group: "{{ azure_manage_networking_stack_resource_group }}"
    tags: "{{ azure_manage_networking_stack_tags | default(omit) }}"

- name: Create azure subnet
  azure.azcollection.azure_rm_subnet:
    name: "{{ azure_manage_networking_stack_subnet }}"
    virtual_network: "{{ azure_manage_networking_stack_virtual_network }}"
    address_prefixes_cidr: "{{ azure_manage_networking_stack_subnet_address_prefixes_cidr }}"
    resource_group: "{{ azure_manage_networking_stack_resource_group }}"
    security_group: "{{ azure_manage_networking_stack_security_group | default(omit) }}"
