---
- name: Check that resource group exists
  azure.azcollection.azure_rm_resourcegroup_info:
    name: "{{ azure_resource_group }}"
  register: result

- name: Create resource group when it does not exists
  ansible.builtin.include_role:
    name: cloud.azure_ops.resource_group
  when: result.resourcegroups | length == 0

- name: Create azure virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    location: "{{ azure_region }}"
    name: "{{ azure_virtual_network }}"
    address_prefixes_cidr: "{{ azure_vnet_address_prefixes_cidr }}"
    resource_group: "{{ azure_resource_group }}"
    tags: "{{ azure_tags | default(omit) }}"

- name: Create azure subnet
  azure.azcollection.azure_rm_subnet:
    name: "{{ azure_subnet }}"
    virtual_network: "{{ azure_virtual_network }}"
    address_prefix_cidr: "{{ azure_subnet_address_prefixes_cidr }}"
    resource_group: "{{ azure_resource_group }}"
    security_group: "{{ azure_security_group | default(omit) }}"
