---
- name: Delete resource group
  ansible.builtin.import_role:
    name: cloud.azure_ops.azure_manage_resource_group
  vars:
    azure_force_delete_nonempty: true
    azure_force_delete_locked: true
  when: delete_option == 'all'

- name: Delete virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    state: absent
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_virtual_network }}"
  when: delete_option == 'virtual_network'

- name: Delete subnet
  azure.azcollection.azure_rm_subnet:
    state: absent
    resource_group: "{{ azure_resource_group }}"
    virtual_network: "{{ azure_virtual_network }}"
    name: "{{ azure_subnet }}"
  when: delete_option == 'subnet'
