---
- name: Check operation validation
  ansible.builtin.fail:
    msg: Please provide operation as 'create' or 'delete'
  when: operation not in ['create', 'delete']

- name: Check Resource group name
  ansible.builtin.fail:
    msg: Azure Resource group name must be defined as azure_resource_group
  when: azure_resource_group is not defined

- name: Create or delete resource group
  ansible.builtin.include_tasks: "{{ operation }}.yml"
