- name: Migrate a web app application from one region to another region
  hosts: localhost
  gather_facts: no

  collections:
  - cloud.azure_roles
  - azure.azcollection

  vars_files:
  - vars/vmss_migrate_vars.yml

  tasks:
  - name: Pre-flight check
    fail:
      msg: "Source Azure Resource group must be defined as source_resource_group"
    when: source_resource_group is not defined

  - name: Pre-flight check
    fail:
      msg: "Destination Azure Resource group must be defined as destination_resource_group"
    when: destination_resource_group is not defined

  - name: Pre-flight check
    fail:
      msg: "Source and Destination Azure resource group can not be same"
    when: source_resource_group == destination_resource_group

  - name: Gather information about Source VM Scale Set
    azure_rm_virtualmachinescaleset_info:
      resource_group: "{{ source_resource_group }}"
      name: "{{ azure_vm_name }}ss"
    register: src_vm_info

  - name: Pre-flight check
    fail:
      msg: "Couldn't find web app resources in source_resource_group"
    when: src_vm_info.vmss | length == 0

  - name: Create application infrastructure
    block:
      - name: Create application infrastructure
        import_role:
          name: scale_virtual_machine
        vars:
          azure_resource_group: "{{ destination_resource_group }}"
          azure_region: "{{ destination_region }}"
          azure_number_vm: "{{ src_vm_info.vmss.0.sku.capacity }}"
          azure_vm_image: "{{ src_vm_info.vmss.0.properties.virtualMachineProfile.storageProfile.imageReference }}"
          azure_vm_size: "{{ src_vm_info.vmss.0.sku.name }}"
          azure_load_balancer:
            domain_name: "{{ destination_resource_group  | replace('_', '-')  }}-{{ destination_region  | replace('_', '-')  }}-webapp1"
            name: "{{ source_resource_group }}-lb"
            public_ip_name: "{{ source_resource_group }}-lb-public-ipp"
            backend_address_pool: "{{ source_resource_group }}-vm-pool"
          operation: create
    rescue:
      - debug:
          msg: "Failed to migrate, cleaning up destination resource group"

      - name: Delete application infrastructure
        import_role:
          name: scale_virtual_machine
        vars:
          azure_resource_group: "{{ destination_resource_group }}"
          operation: delete

      - fail:
          msg: "Failed to migrate"

- name: Deploy resource from Bastion Host
  hosts: bastion
  gather_facts: no

  vars:
    ansible_venv_path: "~/venv"
    application_data: "/tmp/controller"
    application_image: "controller-image"
    application_container: "controller-container"
    application_config: "/tmp/controller/config.txt"

  vars_files:
  - vars/vmss_migrate_vars.yml

  tasks:
  - name: Update ssh_config
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regex: "{{ item.regex }}"
      line: "{{ item.line }}"
    loop:
      - regex: "^(# *)?ClientAliveInterval"
        line: "ClientAliveInterval  1200"
      - regex: "^(# *)?ClientAliveCountMax"
        line: "ClientAliveCountMax 3"
    become: true

  - name: Ensure python3 is installed
    yum:
      name:
        - python3
        - python-virtualenv
        - sshpass
        - git
      state: present
    become: true

  - name: Create virtualenv
    shell: "virtualenv --python python3 {{ ansible_venv_path }}"

  - name: Upgrade pip
    shell: "{{ ansible_venv_path }}/bin/pip install --upgrade pip"

  - name: Install Ansible into virtualenv
    shell: '{{ ansible_venv_path }}/bin/pip install "ansible==2.10.*"'

  - name: Create application directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ ansible_venv_path }}/playbook"
      - "{{ ansible_venv_path }}/playbook/tasks"

  - name: Create inventory file
    template:
      src: workers.j2
      dest: "{{ ansible_venv_path }}/playbook/inventory.yaml"

  - name: Create vars file
    template:
      src: application-data.j2
      dest: "{{ ansible_venv_path }}/playbook/vars.yaml"
    vars:
      azure_postgresql_name: "{{ source_resource_group | replace('_', '-') }}-dbserver"

  - name: Copy playbook file
    copy:
      src: deploy-app.yml
      dest: "{{ ansible_venv_path }}/playbook/play.yaml"

  - name: Git clone ensure-docker role
    git:
      repo: "https://opendev.org/zuul/zuul-jobs.git"
      dest: "{{ ansible_venv_path }}/playbook/zuul-jobs"

  - name: Deploy application
    shell: "source {{ ansible_venv_path }}/bin/activate; ansible-playbook play.yaml -i inventory.yaml -e '@vars.yaml' -v -f {{ playbook_number_forks }}"
    environment:
      ANSIBLE_ROLES_PATH: "{{ ansible_venv_path }}/playbook/zuul-jobs/roles"
    args:
      chdir: "{{ ansible_venv_path }}/playbook"

- hosts: localhost
  gather_facts: no

  collections:
  - cloud.azure_roles
  - azure.azcollection

  vars_files:
  - vars/vmss_migrate_vars.yml

  tasks:
  - block:
      - name: Check that you can connect (GET) to a page and it returns a status 200
        uri:
          url: "http://{{ load_balancer_public_ip }}:5000"
        when: load_balancer_public_ip is defined
    rescue:
      - debug:
          msg: "Failed to reach the given URL at http://{{ load_balancer_public_ip }}:5000, cleaning up destination resource group"

      - name: Delete application infrastructure
        import_role:
          name: scale_virtual_machine
        vars:
          azure_resource_group: "{{ destination_resource_group }}"
          operation: delete

      - fail:
          msg: "Failed to reach the given URL at http://{{ load_balancer_public_ip }}:5000"

  - set_fact:
      azure_virtual_network: "{{ source_resource_group }}-vnet"
      azure_subnet: "{{ source_resource_group }}-subnet"
      azure_security_group: "{{ source_resource_group }}-nsg"
      azure_load_balancer:
        name: "{{ source_resource_group }}-lb"
        public_ip_name: "{{ source_resource_group }}-lb-public-ip"

  - name: Remove Bastion host
    azure_rm_virtualmachine:
      resource_group: "{{ source_resource_group }}"
      name: "{{ azure_vm_name }}bastion"
      state: absent

  - name: Remove Virtual machine scale set
    azure_rm_virtualmachinescaleset:
      resource_group: "{{ source_resource_group }}"
      name: "{{ azure_vm_name }}ss"
      state: absent

  - name: Delete virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ source_resource_group }}"
      name: "{{ azure_virtual_network }}"
      state: absent

  - name: Delete subnet
    azure_rm_subnet:
      resource_group: "{{ source_resource_group }}"
      virtual_network: "{{ azure_virtual_network }}"
      name: "{{ azure_subnet }}"
      state: absent

  - name: Delete load balancer
    azure_rm_loadbalancer:
      resource_group: "{{ source_resource_group }}"
      name: "{{ azure_load_balancer.name }}"
      state: absent

  - name: Delete a public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ source_resource_group }}"
      name: "{{ azure_load_balancer.public_ip_name }}"
      state: absent

  - name: Delete networking security group
    azure_rm_securitygroup:
      resource_group: "{{ source_resource_group }}"
      name: "{{ azure_security_group }}"
      state: absent

  - debug:
      msg: "Web application accessible at http://{{ load_balancer_public_ip }}:5000"
